// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4HV5HwNng8V-EhZyGsqEEpqtYOpbyaQ',
    appId: '1:903118596740:web:cf016570b4ddb46083f0d1',
    messagingSenderId: '903118596740',
    projectId: 'coursermic',
    authDomain: 'coursermic.firebaseapp.com',
    storageBucket: 'coursermic.appspot.com',
    measurementId: 'G-8FCPQTVHYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQ0Z0Fcb_LFnF8vwY_EqWFUalMOONa7Y',
    appId: '1:903118596740:android:b9455767b2dfaf4983f0d1',
    messagingSenderId: '903118596740',
    projectId: 'coursermic',
    storageBucket: 'coursermic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpfCqEvVRbrAnhD1DENHFosbXiMfcVr30',
    appId: '1:903118596740:ios:1b8384e224c4463683f0d1',
    messagingSenderId: '903118596740',
    projectId: 'coursermic',
    storageBucket: 'coursermic.appspot.com',
    iosClientId: '903118596740-15iqts5nivs0jdhhvdka25s4kmi3b34r.apps.googleusercontent.com',
    iosBundleId: 'com.example.capston',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpfCqEvVRbrAnhD1DENHFosbXiMfcVr30',
    appId: '1:903118596740:ios:1b8384e224c4463683f0d1',
    messagingSenderId: '903118596740',
    projectId: 'coursermic',
    storageBucket: 'coursermic.appspot.com',
    iosClientId: '903118596740-15iqts5nivs0jdhhvdka25s4kmi3b34r.apps.googleusercontent.com',
    iosBundleId: 'com.example.capston',
  );
}
